#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sun Jan 15 23:21:20 2012

import wx

# begin wxGlade: extracode
# TODO: use wxWidget 2.9 wxTreeCtrl
from wx.gizmos import TreeListCtrl
# TODO: use wxWidget 2.9 wxTreeCtrl
from wx.gizmos import TreeListCtrl
# end wxGlade


class wxITI1480AMainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxITI1480AMainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_OPEN, "&Open", "Open file", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_SAVE, "&Save", "Save current capture", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_EXIT, "&Exit", "", wx.ITEM_NORMAL)
        self.menubar.Append(wxglade_tmp_menu, "&File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(4, "&Start", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(5, "&Pause", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_STOP, "S&top", "", wx.ITEM_NORMAL)
        self.menubar.Append(wxglade_tmp_menu, "&Capture")
        self.SetMenuBar(self.menubar)
        # Menu Bar end
        self.statusbar = self.CreateStatusBar(3, 0)
        
        # Tool Bar
        self.toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL | wx.TB_FLAT | wx.TB_DOCKABLE | wx.TB_TEXT)
        self.SetToolBar(self.toolbar)
        self.toolbar.AddLabelTool(wx.ID_OPEN, "Open", wx.Bitmap("images/fileopen.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Open file", "")
        self.toolbar.AddLabelTool(wx.ID_SAVE, "Save", wx.Bitmap("images/filesave.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Save current capture", "")
        self.toolbar.AddSeparator()
        self.toolbar.AddLabelTool(4, "Start", wx.Bitmap("images/player_play.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Start cature", "")
        self.toolbar.AddLabelTool(5, "Pause", wx.Bitmap("images/player_pause.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_CHECK, "Pause/continue capture", "")
        self.toolbar.AddLabelTool(wx.ID_STOP, "Stop", wx.Bitmap("images/player_stop.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Terminate capture", "")
        # Tool Bar end
        self.device_notebook = wx.Notebook(self, -1, style=0)
        self.capture_list = TreeListCtrl(self.device_notebook, -1, style=wx.TR_HIDE_ROOT | wx.TR_NO_BUTTONS | wx.TR_ROW_LINES | wx.TR_FULL_ROW_HIGHLIGHT)
        self.bus_list = TreeListCtrl(self.device_notebook, -1, style=wx.TR_HIDE_ROOT | wx.TR_NO_BUTTONS | wx.TR_ROW_LINES | wx.TR_FULL_ROW_HIGHLIGHT)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.onOpen, id=wx.ID_OPEN)
        self.Bind(wx.EVT_MENU, self.onSave, id=wx.ID_SAVE)
        self.Bind(wx.EVT_MENU, self.onExit, id=wx.ID_EXIT)
        self.Bind(wx.EVT_MENU, self.onStart, id=4)
        self.Bind(wx.EVT_MENU, self.onPause, id=5)
        self.Bind(wx.EVT_MENU, self.onStop, id=wx.ID_STOP)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxITI1480AMainFrame.__set_properties
        self.SetTitle("ITI1480A-linux")
        self.SetSize((800, 600))
        self.statusbar.SetStatusWidths([-1, 150, 26])
        # statusbar fields
        statusbar_fields = ["", "", ""]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        self.toolbar.SetToolBitmapSize((16, 16))
        self.toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxITI1480AMainFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        self.device_notebook.AddPage(self.capture_list, "Capture")
        self.device_notebook.AddPage(self.bus_list, "Bus")
        sizer_2.Add(self.device_notebook, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

    def onOpen(self, event):  # wxGlade: wxITI1480AMainFrame.<event_handler>
        print "Event handler `onOpen' not implemented!"
        event.Skip()

    def onSave(self, event):  # wxGlade: wxITI1480AMainFrame.<event_handler>
        print "Event handler `onSave' not implemented!"
        event.Skip()

    def onExit(self, event):  # wxGlade: wxITI1480AMainFrame.<event_handler>
        print "Event handler `onExit' not implemented!"
        event.Skip()

    def onStart(self, event):  # wxGlade: wxITI1480AMainFrame.<event_handler>
        print "Event handler `onStart' not implemented!"
        event.Skip()

    def onPause(self, event):  # wxGlade: wxITI1480AMainFrame.<event_handler>
        print "Event handler `onPause' not implemented!"
        event.Skip()

    def onStop(self, event):  # wxGlade: wxITI1480AMainFrame.<event_handler>
        print "Event handler `onStop' not implemented!"
        event.Skip()

# end of class wxITI1480AMainFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    main_frame = wxITI1480AMainFrame(None, -1, "")
    app.SetTopWindow(main_frame)
    main_frame.Show()
    app.MainLoop()
